#!/usr/bin/env bash

function main {
  set -x

  if [[ -n "${HOME_SSH_USER_KEY_PUB:-}" ]]; then
    echo "${HOME_SSH_USER_KEY_PUB}" | base64 -d | sudo tee /etc/ssh/ssh_user_key.pub >/dev/null
    echo TrustedUserCAKeys /etc/ssh/ssh_user_key.pub | sudo tee -a /etc/ssh/sshd_config
  fi

  if [[ -n "${HOME_SSH_HOST_ECDSA_KEY:-}" ]]; then
    echo "${HOME_SSH_HOST_ECDSA_KEY}" | base64 -d | sudo tee /etc/ssh/ssh_host_ecdsa_key >/dev/null
    echo "${HOME_SSH_HOST_ECDSA_KEY_CERT_PUB}" | base64 -d | sudo tee /etc/ssh/ssh_host_ecdsa_key-cert.pub >/dev/null
    echo HostKey /etc/ssh/ssh_host_ecdsa_key | sudo tee -a /etc/ssh/sshd_config
    echo HostCertificate /etc/ssh/ssh_host_ecdsa_key-cert.pub | sudo tee -a /etc/ssh/sshd_config
  fi

  if [[ ! -r /etc/ssh/ssh_host_rsa_key ]]; then
    sudo rm -v /etc/ssh/ssh_host_*
    sudo dpkg-reconfigure openssh-server
    sudo chown -R app:app /etc/ssh /run
  fi

  #echo LOGLEVEL DEBUG3 | sudo tee -a /etc/ssh/sshd_config

  sudo chown app:app /var/run/docker.sock || true

  exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
}

main "$@"
