repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  #  - repo: https://github.com/pycqa/isort
  #    rev: 5.8.0
  #    hooks:
  #      - id: isort
  #
  #  - repo: https://gitlab.com/pycqa/flake8
  #    rev: 3.9.2
  #    hooks:
  #      - id: flake8
  #        additional_dependencies: [flake8-isort]

  - repo: git://github.com/dnephin/pre-commit-golang
    rev: fd0556d9a362a9a184327a4e8cf3c9f0dea3a47b
    hooks:
      - id: go-fmt
