apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: homedir-kaniko-build-
spec:
  arguments:
    parameters:
      - name: repo
      - name: revision
      - name: version
      - name: variant
      - name: base_source
      - name: base_destination
      - name: base_dockerfile
  templates:
    - name: build-base
      steps:
        - - name: build-base
            template: kaniko-build
            arguments:
              parameters:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
                - name: source
                  value: "{{workflow.parameters.base_source}}{{workflow.parameters.variant}}"
                - name: destination
                  value: "{{workflow.parameters.base_destination}}{{workflow.parameters.variant}}-{{workflow.parameters.version}}"
                - name: dockerfile
                  value: "{{workflow.parameters.base_dockerfile}}"
    - name: kaniko-build
      inputs:
        parameters:
          - name: repo
          - name: revision
          - name: source
          - name: destination
          - name: dockerfile
          - name: insecure_pull
            value: "--insecure-pull"
        artifacts:
          - name: source
            path: /src
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{inputs.parameters.revision}}"
      container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--context=/src"
          - "--dockerfile={{inputs.parameters.dockerfile}}"
          - "--destination={{inputs.parameters.destination}}"
          - "--build-arg"
          - "IMAGE={{inputs.parameters.source}}"
          - "--reproducible"
          - "--cache"
          - "--cache-copy-layers"
          - "--insecure"
          - "{{inputs.parameters.insecure_pull}}"
  securityContext:
    runAsNonRoot: false
