tap "homebrew/cask"
tap "github/gh"
tap "git-chglog/git-chglog"

brew "aws-okta"
brew "chamber"
brew "ctop"
brew "drone-cli"
brew "gnupg"
brew "git"
brew "readline"
brew "htop"
brew "jq"
brew "make"
brew "pass"
brew "powerline-go"
brew "rsync"
brew "tmux"
brew "unzip"
brew "vim"

brew "github/gh/gh"
brew "git-chglog/git-chglog/git-chglog"

cask "1password"
cask "chromedriver"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "lens"
cask "pritunl"
cask "signal"
cask "skitch"
cask "slack"
cask "superduper"
cask "wire"
cask "zerotier-one"
