apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.1.222.100-10.1.222.199
      - 10.1.223.100-10.1.223.199
      - 10.1.224.100-10.1.224.199
