apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.defn.sh
spec:
  group: defn.sh
  scope: Namespaced
  names:
    kind: HelloWorld
    plural: helloworlds
    singular: helloworld
    shortNames:
      - hw
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
