apiVersion: v1
kind: Service
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  ports:
    - name: sshd
      port: 22
      protocol: TCP
      targetPort: sshd
  selector:
    app: sshd
  type: ClusterIP
