#!/usr/bin/env bash

function main {
  set -x

  #echo LOGLEVEL DEBUG3 | sudo tee -a /etc/ssh/sshd_config

  if [[ -d /cm/ssh ]]; then
    mkdir -p ~/.ssh
    cp -v /cm/ssh/* ~/.ssh/
  fi

  exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o Port=2222 -e
}

main "$@"
