#!/usr/bin/env bash

doctl compute firewall -o json list | jq '(reduce .[] as $e ({}; .[$e.name] = $e)) as $fw | { firewall: $fw }' > do-firewall.json
doctl compute volume -o json list | jq '(reduce .[] as $e ({}; .[$e.name] = $e)) as $vol | { volume: $vol }' > do-volume.json
doctl compute ssh-key -o json list | jq '(reduce .[] as $e ({}; .[$e.name] = $e)) as $ssh | { ssh: $ssh }' > do-ssh.json
doctl compute snapshot list -o json| jq '(reduce .[] as $e ({}; .[$e.name] = $e)) as $snap| { snapshot: $snap }' > do-snapshot.json
doctl compute floating-ip -o json list | jq '(reduce .[] as $e ({}; .[$e.ip] = $e)) as $ip | { ip: $ip }' > do-ip.json
cue import -p defn -f do-*.json
rm do-*.json
