apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: defn-
  annotations:
    repo: "https://github.com/defn/hello"
    revision: main
    destination: "k3d-hub.defn.ooo:5000/defn/hello:latest"
spec:
  entrypoint: build
  templates:
    - name: build
      inputs:
        artifacts:
          - name: source
            path: /src
            git:
              repo: "{{workflow.annotations.repo}}"
              revision: "{{workflow.annotations.revision}}"
      container:
        image: gcr.io/kaniko-project/executor
        args:
          - "--context=/src"
          - "--destination={{workflow.annotations.destination}}"
          - "--insecure"
  securityContext:
    runAsNonRoot: false
