apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
        - name: sshd
          image: defn-sshd
          ports:
            - name: sshd
              containerPort: 2222
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock.host
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
